### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mrshake**
Can someone verify these are the right profile options.

As well, the cmake command listed ends with ../ which doesn't seem right.. shouldn't it be ./ for *nix based systems.

Need to add Windows CMAKE stuff in there as well.

### CODE REVIEW

**Comment by jvetter1** [comment]
Yes, thats correct.

Replace it with the one here
https://github.com/brewtrollergit/brewtroller/blob/develop/README.md. I
updated this but I guess forgot to put it in Official.

Mine has the missing steps. You need to mkdir build, cd build, then do your
steps. That way all the build files go in build/ vs ./

**Comment by mrshake** [comment]
I've copied over your README and added the "example"

**Comment by jvetter1** [comment]
Change "support" to "supported", my typo.

You will see I have instructions for Linux and Ubuntu on Windows, but no
raw windows

**Comment by jvetter1** [comment]
Example is broken, formatting got messed up below it...

**Comment by mrshake** [comment]
Fixed that.  

This will only work for the 2.8 branch correct?

**Comment by jvetter1** [comment]
Correct, the instructions are for develop branch only

**Pull request merged**
